name: Build Totals

on:
  push:
    paths:
      - "public/all/**"

concurrency:
  group: build-totals
  cancel-in-progress: true

jobs:
  build-totals:

    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build totals
        run: node scripts/buildTotals.js

      - name: Commit generated totals
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate totals.json files"
          branch: main
